Fix map
catalyst-team/catalyst pull request #1128
Opened 2021-03-21 19:35 UTC by zkid18

## Before submitting (checklist)

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)?
- [x] Did you check the code style? `catalyst-make-codestyle && catalyst-check-codestyle` (`pip install -U catalyst-codestyle`).
- [x] Did you make sure to update the docs? We use Google format for all the methods and classes.
- [x] Did you check the docs with `make check-docs`?
- [x] Did you write any new necessary tests?
- [x] Did you check that your code passes the unit tests `pytest .` ? 
- [x] Did you add your new functionality to the docs?
- [ ] Did you update the [CHANGELOG](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md)?

## Description

## Related Issue

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

PS
- [x] I know, that I could [join slack](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for pull request discussion.

2021-03-21 19:35 UTC, pep8speaks commented
Hello @zkid18! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`catalyst/contrib/datasets/movie_lens.py`](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py):

> [Line 16:1](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L16): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 18:67](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L18): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 19:54](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L19): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 23:79](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L23): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 51:37](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L51): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 56:13](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L56): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 58:13](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L58): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 62:5](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L62): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 84:1](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L84): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 101:20](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L101): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 101:22](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L101): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 102:30](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L102): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 102:32](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L102): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 102:32](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L102): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 107:17](https://github.com/catalyst-team/catalyst/blob/27543bdba41bce444b50d48ca06f589f9275fac6/catalyst/contrib/datasets/movie_lens.py#L107): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2021-03-21 19:46 UTC, Scitator submitted a review, later dismissed

2021-03-21 19:46 UTC, Scitator commented on catalyst/contrib/datasets/movie_lens.py
> +import os
do we need it?

2021-03-21 19:46 UTC, Scitator commented on catalyst/utils/metrics/hitrate.py
> +"""
do we need this file?

2021-03-21 19:46 UTC, Scitator commented on catalyst/utils/metrics/tests/test_hitrate.py
> +import torch
and this one?

2021-03-22 05:19 UTC, Scitator requested changes, later dismissed

2021-03-22 05:19 UTC, Scitator commented on catalyst/metrics/tests/test_avg_precision.py
> +    assert np.allclose(map_at3, 0.667, atol=1e-3)
```suggestion
    assert np.allclose(map_at3, 0.6675, atol=1e-3)
```

2021-03-22 05:19 UTC, Scitator commented on catalyst/metrics/tests/test_avg_precision.py
> +    assert np.allclose(map_at5, 0.6417, atol=1e-3)
```suggestion
    assert np.allclose(map_at5, 0.6425, atol=1e-3)
```

2021-03-22 05:19 UTC, Scitator commented on catalyst/metrics/tests/test_avg_precision.py
> +
let's add the comments like:
```
01: (1.0 + 0.0) / 2 = 0.5
03: ((1 + 0.67)/2 + 0.5) / 2 = 0.6675
05: ((1 + 0.67)/2 + (0.5 + 0.4)/2) / 2 = 0.6425
10: ((1 + 0.67 + 0.5 + 0.44 + 0.5)/5 + (0.5 + 0.4 + 0.43)/3 ) / 2  = 0.53
```

2021-03-27 16:53 UTC, zkid18 commented
Close this PR in the regard of https://github.com/catalyst-team/catalyst/pull/1140

2021-03-27 16:53 UTC, closed without merging