callbacks refactoring; bugfixes and plotly for notebooks
catalyst-team/catalyst pull request #127
Opened 2019-03-22 08:32 UTC by Scitator

- callbacks refactoring, improved 1Cycle
- bugfixes for logging & custom shedulers
- plotly for notebooks

2019-03-23 08:09 UTC, TezRomacH commented on requirements.txt
>  scikit-image
btw, let's freeze any other dependencies?

2019-03-23 13:39 UTC, hexfaker requested changes

2019-03-23 13:39 UTC, hexfaker commented on catalyst/utils/plotly.py
> +from typing import List, Dict, Union, Optional
Credits pls

2019-03-23 13:39 UTC, hexfaker commented on examples/_tests_mnist_stages/config2.yml
> +#        div_factor: 3
What's the reason for leaving commented code? Better remove it anyway

2019-03-23 13:39 UTC, hexfaker commented on catalyst/dl/callbacks/schedulers.py
> +            self.init_lr
Formatting is weird. Mb split into multiple statements?

2019-03-23 13:41 UTC, hexfaker commented on catalyst/utils/plotly.py
> +from typing import List, Dict, Union, Optional
To @belskikh

2019-03-24 08:58 UTC, hexfaker approved these changes

2019-03-24 14:00 UTC, merged