Movielens20m dataset
catalyst-team/catalyst pull request #1336
Opened 2021-10-27 11:22 UTC by zkid18

### Pull Request FAQ
- [documentation](https://catalyst-team.github.io/catalyst/)
- [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

## Description

Movielens 20M dataset for RecSys.
Current implementation progress:

[x] download dataset
[x] parser and pre-processing for the rating.csv
[x] user-based train/test splitter
[ ] interaction matrix generation
[ ] seq dataset generation 
[ ] upload dataset in sparse format in PyTorch.

I stuck with a proper final representation of the dataset. 

Couple words on Movielens20M dataset. 
1-5 can be considered as context-based information, while `rating` provides the user interaction data. Hence we can omit 1-5 at that time. 

```
    The data are contained in six files: 
    1. genome-scores.csv 
    2. genome-tags.csv 
    3. links.csv 
    4. movies.csv
    5. tags.csv  
    6. ratings.csv
 ```
 
`rating.csv head -5`

```
   userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580
```

So I have split the dataset randomly by users. I need to better understand how the dataset for the sequential RecSys should look like. 

## Related Issue

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### Checklist
- [ ] Have you updated tests for the new functionality?
- [ ] Have you added your new classes/functions to the docs?
- [ ] Have you updated the [CHANGELOG](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md)?
- [ ] Have you run [colab minimal CI/CD](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/colab_ci_cd.ipynb) with `latest` and `minimal` requirements?
- [ ] Have you checked XLA integration with [single](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/Catalyst_XLA_single_process.ipynb) and [multiple](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/Catalyst_XLA_multi_process.ipynb) processes?

2021-10-27 11:22 UTC, pep8speaks commented
Hello @zkid18! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











There are currently no PEP 8 issues detected in this Pull Request. Cheers! :beers: 

##### Comment last updated at 2021-12-27 05:25:19 UTC

2021-10-28 04:29 UTC, Scitator reviewed
it would be great if we could correct the code style and add a few usage examples for the dataset

2021-10-28 04:29 UTC, Scitator commented on tmp_data/MovieLens20M/raw/ml-20m/README.txt
> +Summary
not sure about this file ;)

2021-11-08 10:47 UTC, zkid18 commented
https://colab.research.google.com/drive/1l6mpAWBKbkEWILnz9ThwpAoTQDCXkG-M?authuser=1#scrollTo=HkzzfT1moccj&uniqifier=1

Colab to test MovieLens20m

2021-11-08 10:48 UTC, zkid18 commented on tmp_data/MovieLens20M/raw/ml-20m/README.txt
> +Summary
oops

2021-11-20 19:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/catalyst-team/catalyst?pullRequest=1336) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/catalyst-team/catalyst?pullRequest=1336) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/catalyst-team/catalyst?pullRequest=1336) it.</sub>

2021-11-29 16:31 UTC, Scitator submitted a review, later dismissed
LGTM

2021-12-20 04:30 UTC, Scitator requested changes, later dismissed
todo: `torch>=1.3.0` ;)

2021-12-20 16:43 UTC, Scitator submitted a review, later dismissed

2021-12-20 16:43 UTC, Scitator commented on requirements/requirements-cv.txt
> +torchvision=0.5.0
0.4.1

2021-12-20 16:43 UTC, Scitator commented on requirements/requirements-ml.txt
> +pandas>=1.1.1
1.0?

2021-12-24 14:44 UTC, Scitator commented on requirements/requirements-ml.txt
> +pandas>=1.1.1
1.0? or `0.25.0`

2021-12-24 14:47 UTC, Scitator commented on tests/catalyst/contrib/datasets/test_movielens_20m.py
> +    MovieLens20M("./tmp_data", download=True, sample=True)
could we use TemporaryDirectory? like https://github.com/catalyst-team/catalyst/blob/e1d78b7dd568c4d5cd94be417d6d8b93ef27b2e5/tests/catalyst/runners/test_train_flags.py

2021-12-24 14:47 UTC, Scitator requested changes, later dismissed
comments ;)

2021-12-27 05:31 UTC, merged