Multi-headed Value functions
catalyst-team/catalyst pull request #198
Opened 2019-05-26 15:25 UTC by KhrulkovV

Implementation of the algorithm from [Hyperbolic Discounting and Learning over
Multiple Horizons](https://arxiv.org/pdf/1902.06865.pdf), as described in the section devoted to Atari experiments (using only the last head for playing, learning Q-functions for multiple gammas are interpreted as _auxiliary tasks_).

2019-05-27 12:50 UTC, Scitator requested changes
based on slack discussion

2019-05-28 05:00 UTC, Scitator requested changes

2019-05-28 05:00 UTC, Scitator commented on catalyst/rl/agents/critic.py
> +            return self.head_net.hyperbolic_constant
can you make it 1.0 for `num_heads == 1` case?

2019-05-28 05:00 UTC, Scitator commented on catalyst/rl/agents/critic.py
> +            return self.head_net.hyperbolic_constant
maybe just always return self.head_net.hyperbolic_constant without any additional logic?

2019-05-28 05:00 UTC, Scitator commented on catalyst/rl/agents/head.py
> +        hyperbolic_constant=0.01
annotations, like float & int, please

2019-05-28 05:00 UTC, Scitator commented on catalyst/rl/agents/head.py
> +    def _build_head(
place it just after the `__init__` please, to store all the private methods before the public one

2019-05-28 05:00 UTC, Scitator commented on catalyst/rl/offpolicy/algorithms/dqn.py
> +        if self._num_heads == 1:
during critic forward:
```
# B x num_heads x num_outputs x num_atoms
# if num_heads == 1, squeeze it out not to crash other algorithms
return torch.stack(x, dim=1).squeeze(1)
```
and now `unsqueeze(1)`?

what do you think about making critic always output `[bs; num_heads; num_outputs; num_atoms]` (so it would  always have output of deterministic shape)? and refactor all other algorithms to use correct shape (add/remove `squeeze/unsqueeze` blocks)?

2019-05-28 05:00 UTC, Scitator commented on catalyst/rl/offpolicy/algorithms/dqn.py
> +        q_target_t = rewards_t + (1 - done_t * gammas * q_values_tp1.detach())
something strange with brackets happened here... can you please check the correctness?

2019-05-28 05:00 UTC, Scitator commented on catalyst/rl/offpolicy/algorithms/dqn.py
> +        critic = self.critic_fn
do not you mind to write shapes for all the tensors in `_base_loss/_categorical_loss/_quantile_loss` ?
because of many reshapes and transforms it's a little bit hard to understand what is going on without understanding tensor shapes

2019-05-29 15:03 UTC, KhrulkovV commented on catalyst/rl/agents/head.py
> +    def _build_head(
Fixed.

2019-05-29 15:03 UTC, KhrulkovV commented on catalyst/rl/agents/critic.py
> +            return self.head_net.hyperbolic_constant
Fixed, thanks.

2019-05-29 15:03 UTC, KhrulkovV commented on catalyst/rl/offpolicy/algorithms/dqn.py
> +        if self._num_heads == 1:
Sounds good, will try to implement.

2019-05-29 15:03 UTC, KhrulkovV commented on catalyst/rl/offpolicy/algorithms/dqn.py
> +        q_target_t = rewards_t + (1 - done_t * gammas * q_values_tp1.detach())
Fixed, thanks.

2019-06-11 06:07 UTC, Scitator approved these changes

2019-06-11 06:34 UTC, merged

2021-05-15 17:19 UTC, rfali commented
@Scitator I can't seem to files that were changed as part of this PR in this repo. I am not sure what I am missing. There is the older Catalyst Repo [v1](https://github.com/catalyst-team/catalyst-rl/blob/master/catalyst_rl/rl/offpolicy/algorithms/dqn.py) that has some parts of this. Where is the v2 dqn.py?

@KhrulkovV I have a question about this implementation. The way you have used the hyperbolic gammas on this [line](https://github.com/catalyst-team/catalyst-rl/blob/ec18ff4a58b6d00652f772231db8de86debb4b3d/catalyst_rl/rl/offpolicy/algorithms/dqn.py#L20) is different from the original [source code](https://github.com/google-research/google-research/tree/master/hyperbolic_discount) from the authors. Your implementation (not sure because of Catalyst RL v1 v2 confusion) uses these gammas for evaluating the Bellman updates, whereas these gammas are used by the authors to estimate the integral (see [here](https://github.com/google-research/google-research/blob/672c1857ba56c195000d0e0d38a46b10579b7c03/hyperbolic_discount/hyperbolic_dqn_agent.py#L119)). Since you did not implement the hyperbolic acting policy (integrate over all the heads) and used only the largest gamma (last head) for actions, while still computing loss over all heads, I think the gammas you obtain still need to raised to the k power as is done on this [line](https://github.com/google-research/google-research/blob/672c1857ba56c195000d0e0d38a46b10579b7c03/hyperbolic_discount/hyperbolic_dqn_agent.py#L130). These are the self.gammas that are used in the Bellman updates as [here](https://github.com/google-research/google-research/blob/672c1857ba56c195000d0e0d38a46b10579b7c03/hyperbolic_discount/hyperbolic_dqn_agent.py#L264). 

Just thought to run this by you, since I could definitely be wrong. I am implementing this paper in another library and this is the only other work that implements this technique. By the way, do you have an example of how I can use this PR to a simple gym environment?

2021-05-15 17:22 UTC, rfali commented
@KhrulkovV  please correct me if I am wrong, if I concatenate the q-values learned over all-heads (final layer), and then slice the resulting tensor to get individual q-values, and keep the rest as same (calculate loss for each and aggregate), that would still be equivalent?