`FORCE_JPEG_TURBO`
catalyst-team/catalyst pull request #239
Opened 2019-06-19 09:21 UTC by bagxi

2019-06-19 11:44 UTC, hexfaker requested changes

2019-06-19 11:44 UTC, hexfaker commented on catalyst/utils/image.py
> +import jpeg4py as jpeg
Import should be moved to lines 35-36 (inside condition) because now it's optional and should be removed from requirements.

2019-06-19 11:44 UTC, hexfaker commented on requirements.txt
> +jpeg4py
This is optional dependency and should not be present in requirements

2019-06-19 12:27 UTC, hexfaker approved these changes

2019-06-19 18:40 UTC, Scitator commented
try-except is quite slow in python and can level all jpeg4py speed.
So, my suggestion is to follow [this ods thread](https://opendatascience.slack.com/archives/C044B7CSQ/p1560240300231300)
For example, you can use something like [this](https://github.com/catalyst-team/catalyst/blob/master/catalyst/utils/compression.py#L9) to handle import only once and store some global constant like `JPEG4PY_ENABLED`. Nevertheless, do not remember to check jpeg4py import and decode methods before enabling this flag :)

2019-06-19 18:41 UTC, Scitator requested changes
we need something like `JPEG4PY_ENABLED` to speedup this solution

2019-06-20 13:04 UTC, Scitator requested changes

2019-06-20 13:04 UTC, Scitator commented on catalyst/utils/image.py
> +if os.environ.get('FORCE_JPEG_TURBO', False):
please use " to follow lib standarts

2019-06-20 13:04 UTC, Scitator commented on catalyst/utils/image.py
> +            "To install libjpeg-turbo, see `http://bfy.tw/OC7m`."
I think, it's better to link jpeg4py and libjpeg-turbo installation directly

2019-06-20 13:04 UTC, Scitator commented on catalyst/utils/image.py
> +    if JPEG4PY_ENABLED and rootpath.endswith(("jpg", "JPG", "jpeg", "JPEG")):
`rootpath`? or `uri`?

2019-06-20 16:33 UTC, Scitator requested changes

2019-06-20 16:33 UTC, Scitator commented on catalyst/utils/image.py
> +        img = jpeg.JPEG(uri).decode()
you also need to force grayscale if specified

2019-06-21 11:26 UTC, merged