Fixed gradient tracking
catalyst-team/catalyst pull request #679
Opened 2020-02-25 11:27 UTC by pdanilov

## Description

Fixed storing gradients in OptimizerCallback

## Related Issue

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have checked the code-style using `make check-codestyle`.
- [ ] I have written tests for all new methods and classes that I created.
- [x] I have written the docstring in Google format for all the methods and classes that I used.
- [x] I have checked the docs using `make check-docs`.
- [ ] I have read I need to click 'Login as guest' to see Teamcity build logs.

2020-02-27 06:39 UTC, Scitator commented
Dear @pdanilov ,
could you please write any test to check, that callback works correctly? and also show how it should work :)

2020-02-27 07:36 UTC, pdanilov commented
What is the location for tests of callbacks?
I can only locate catalyst/utils/tests/ in which there are no tests for callbacks

2020-02-28 06:38 UTC, Scitator commented
you can create ones into `catalyst/core/callbacks/tests/*.py`
there should be more someday :)

2020-03-04 18:19 UTC, pdanilov commented
I'm in trouble with tests, because I don't understand how to forward some dummy experiment class (for example, from cifar-simple) into SupervisedRunner, when we deal not with configs, but with the core code of framework.

2020-03-05 06:33 UTC, Scitator commented
@pdanilov you can use Experiment test as an example (`https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiment/tests/test_supervised.py`)
and just do something like
```
runner = SupervisedRunner()
runner.experiment = SupervisedExperiment()
runner._prepare_for_stage("train")

batch = ...
runner._run_batch(batch)

// check runner.state

```

2020-03-05 09:54 UTC, pdanilov commented
Yeah, that's exactly what I am looking for, but Catalyst doesn't provide mechanics like that% you cannot set experiment field into your runner. Your runner can only create local variable experiment as an instance of `_default_experiment`, and the run this experiment inside train method.

https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/runner/supervised.py#L199-L218

2020-03-09 17:19 UTC, pdanilov commented
@Scitator any ideas?

2020-03-10 10:45 UTC, Scitator commented
Sorry, could not understand you issue. You can use Experiment or State to store whatever you need.
Moreover, the example code is fully working one.

PS. btw, could you please merge with current master?

2020-03-13 18:25 UTC, Scitator commented
@pdanilov could you please merge with master?
we have a bunch of updates :)

2020-03-14 13:09 UTC, pdanilov commented
ok

2020-03-21 15:39 UTC, Scitator commented
@pdanilov could you please fix codestyle issues?

2020-03-27 15:19 UTC, pdanilov commented
Ready for merge

2020-03-31 18:45 UTC, pdanilov commented
@Scitator merge?

2020-04-09 10:11 UTC, Scitator requested changes

2020-04-09 10:11 UTC, Scitator commented on catalyst/core/callbacks/optimizer.py
> +                output=state.batch_metrics,
please don't use python inplace return, let's use something like
```
output = self.save_grad_norm(
                model=state.model,
                prefix=self.grad_norm_prefix,
                norm_type=self.norm_type)
# update state.batch_metrics with output
```

2020-04-09 10:11 UTC, Scitator commented on catalyst/core/callbacks/tests/test_optimizer_callback.py
> +    )
I suppose you can use `check=True` during tests

2020-04-11 12:16 UTC, Scitator commented
btw, could you please also move Callaback to `https://github.com/catalyst-team/catalyst/tree/master/catalyst/contrib/dl/callbacks/optimizer.py`? I think, we need to check it for some time, before moving directly to Core.

2020-04-13 06:55 UTC, Scitator commented
@pdanilov Thank you for you contribution!

2020-04-13 06:56 UTC, merged