fix text2embedding
catalyst-team/catalyst pull request #722
Opened 2020-03-24 10:52 UTC by PUSSYMIPT

## Description

Just small fix. In considering we are using `nn.DataParallel` we should call `.config` through `model.module.config`

## Related Issue

https://github.com/catalyst-team/catalyst/issues/700

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [ ] I have checked the code-style using `make check-codestyle`.
- [ ] I have written tests for all new methods and classes that I created.
- [ ] I have written the docstring in Google format for all the methods and classes that I used.
- [ ] I have checked the docs using `make check-docs`.
- [ ] I have read I need to click 'Login as guest' to see Teamcity build logs.

2020-03-24 16:42 UTC, Scitator commented
hi, @PUSSYMIPT 
Thanks for contributing, could you please add some small test for this contrib script?
for example, use the data from [bert classification example](https://github.com/catalyst-team/catalyst/blob/master/examples/distilbert_text_classification/input/train.csv)?
something like,
```
catalyst-contrib text2embedding --in-cvs=./examples/distilbert_text_classification/input/train.csv
```
to the end of our nlp testing script?
https://github.com/catalyst-team/catalyst/blob/master/bin/tests/check_dl_nlp.sh

2020-04-04 14:39 UTC, PUSSYMIPT commented
I'm not sure that `--in-huggingface` is a good idea, but at least it is more convenient to write the test without downloading all bert's weights with `wget`

2020-04-11 12:22 UTC, Scitator requested changes

2020-04-11 12:22 UTC, Scitator commented on catalyst/data/scripts/text2embedding.py
> +            if isinstance(model, torch.nn.DataParallel):
could you please use `utils.is_wrapped_with_???` as more convenient way?

2020-04-11 12:22 UTC, Scitator commented
@PUSSYMIPT thank you for your Pull Request, everything looks good.
Please merge with master branch and let's merge it out!

2020-04-13 06:57 UTC, Scitator commented
@PUSSYMIPT Thank you for your contribution!

2020-04-13 06:57 UTC, merged