[WIP] movie lens dataloader
catalyst-team/catalyst pull request #903
Opened 2020-08-02 13:38 UTC by zkid18

## Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)?
- [x] Did you check the code style? `catalyst-make-codestyle && catalyst-check-codestyle` (`pip install -U catalyst-codestyle`).
- [x] Did you make sure to update the docs? We use Google format for all the methods and classes.
- [x] Did you check the docs with `make check-docs`?
- [ ] Did you write any new necessary tests?
- [x] Did you add your new functionality to the docs?
- [ ] Did you update the [CHANGELOG](https://github.com/catalyst-team/catalyst/CHANGELOG.md)?
- [x] **You can use 'Login as guest' to see Teamcity build logs.**

## Description

The PR motivation to enrich catalyst dataset with movie-lens-100k for recsys purposes. 
The PR is still under development so any suggestions and comments appreciated. 

I tired to follow the MNIST [example](https://github.com/catalyst-team/catalyst/blob/f99e08b739bafa668276cd0da2c5fb2d1e430d6e/catalyst/contrib/datasets/mnist.py) but seems that PyTorch's Dataset is not an optimal solution for the movielens. 

For interaction matrix we need an abstract class with 
```
    def __getitem__(self, item_index, user_index):
        raise NotImplementedError

    def __len__(self):
        """ (user_dim, item_dim) """
        raise NotImplementedError
```
While PyTorch Dataset [provides](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#Dataset
) support  the single way of sampling data from the dataset given an index.

This PR describes the download and parsing part, but doesn't compile with PyTorch protocol. 

## Related Issue

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

2020-08-02 13:38 UTC, pep8speaks commented
Hello @zkid18! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`catalyst/contrib/datasets/movie_lens.py`](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py):

> [Line 13:80](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 20:1](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L20): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 22:67](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L22): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 23:54](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L23): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 24:80](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L24): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 27:79](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L27): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 55:37](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L55): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 68:14](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L68): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 72:19](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L72): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 72:21](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L72): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 84:71](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L84): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 90:1](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L90): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 102:1](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L102): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 107:1](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L107): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 120:12](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L120): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 142:5](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L142): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 168:1](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L168): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 171:1](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L171): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 173:5](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L173): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 180:23](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L180): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 183:23](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L183): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 185:1](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L185): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 186:23](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L186): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 186:51](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L186): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 186:53](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L186): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 189:23](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L189): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 211:28](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L211): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 224:5](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L224): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 244:80](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L244): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 248:80](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L248): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 249:80](https://github.com/catalyst-team/catalyst/blob/550c71cc4b2f614deb919d23d4dd43a6b81447da/catalyst/contrib/datasets/movie_lens.py#L249): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

2020-08-02 15:53 UTC, zkid18 commented
Some ideas towards data representation
https://medium.com/@rinabuoy13/explicit-recommender-system-matrix-factorization-in-pytorch-f3779bb55d74
> First, I create a dataset class which inherits from torch.utils.data.Dataset. The constructor takes two numpy arrays — 2D user-item id array and 1D rating array. I implement `__len__` method which returns the length of dataset, and `__getitem__` which returns tensors of user-item id pairs and ratings.

```
class RatingDataset(Dataset):
  def __init__(self, train, label):
    self.feature_= train
    self.label_= label
  def __len__(self):
    #return size of dataset
    return len(self.feature_)
  def __getitem__(self, idx):
    return              torch.tensor(self.feature_[idx]),torch.tensor(self.label_[idx])
```

As for another abstract class we can refer this implementation https://github.com/maciejkula/spotlight/blob/master/spotlight/interactions.py
https://github.com/maciejkula/spotlight/blob/master/spotlight/datasets/movielens.py

2020-09-11 18:07 UTC, Scitator requested changes, later dismissed
Looks good, but we need to fix codestyle first :)

2020-09-11 18:07 UTC, Scitator commented on CHANGELOG.md
> +- `MovieLens dataset` loader [#903](https://github.com/catalyst-team/catalyst/pull/903)
looks like we need to change this :)

2020-09-29 15:40 UTC, Scitator commented on CHANGELOG.md
> +- `MovieLens dataset` loader ([#903](https://github.com/catalyst-team/catalyst/pull/903))
looks like we need to move it up :)

2020-10-11 12:07 UTC, merged